# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  setup_circle_ci
end

platform :ios do
  desc "Runs all the tests"
  lane :test do
    run_tests(
      clean: true,
      device: "iPhone 15 Pro (17.5)",
      scheme: "GitHubDemo",
      include_simulator_logs: true,
      xcargs: "-destination-timeout 120"   
    )
  end

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
